trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet restore ./ProofWorks.ArtistOps.Api/ProofWorks.ArtistOps.Api.csproj
  displayName: 'Restore NuGet Packages'

- script: dotnet build ./ProofWorks.ArtistOps.Api/ProofWorks.ArtistOps.Api.csproj --configuration $(buildConfiguration) --no-restore
  displayName: 'Build API Project'